### ISSUE TITLE
Remove (or document) restriction on single process tests.

### ISSUE THREAD

**Issue by hwine** [mozilla-services/pytest-services#19]
If I understand virtual env calling conventions, I think the changes in 8e922fabdad6a626a2f08f70c6ffd283889a6caa are only equivalent to the prior code (explicit activation) if ``os.system`` (and friends) are never used.

Activating a virtual env modifies ``PATH`` in addition to python only changes. Directly invoking a python script from within the virtual env only applies the python changes -- ``PATH`` is unchanged.

Thus, if any code "shelled out" to another script, the results may not be the same, and might lead to hard-to-debug behavior.

**Comment by g-k** [comment]
Should we assume non-install make commands run from an activated venv?

I think we'd need to change:

* non-install commands abort when a check for venv for env vars fails
* readme directions

This might be nice to have a cleaner makefile, but it could also complicate running in CI.

**Comment by hwine** [comment]
Another alternative would be to to have the jenkins job do:
```
source venv/bin/activate && make {{target}}
```
The jenkins job is boilerplate code, isn't it?

**Comment by ajvb** [comment]
Great catch @hwine 

>This might be nice to have a cleaner makefile, but it could also complicate running in CI.

We could have the Dockerfile build the venv into the image, which would then allow for what @hwine suggested.

**Comment by g-k** [comment]
OK I'm going to:

- [ ] update the makefile to:
  - [ ] check if you're running in a venv with the super sophisticated check "does the `VIRTUAL_ENV` env var exist?"
  - [ ] refuse to run commands outside a venv
- [ ] update the docs to say activate the venv first

Locally, people will have to activate their venv but it saves us a bunch of boilerplate.

On Travis CI, tests already run inside a venv so everything should run and we can skip setting up the venv.

On Jenkins, we'll need to source before make like Hal suggested [here](https://github.com/mozilla-services/pytest-services/issues/19#issuecomment-361289539)

In docker, we don't need to run in a virtualenv since we're already in an image.

If someone runs this from a different venv or mounts docker stuff locally that's weird/advanced usage and they're on their own.
